Fix #4 -> implement ParsedAddress struct
kodemartin/rustpostal pull request #7
Opened 2021-12-29 16:50 UTC by rjcortese

2022-01-12 16:41 UTC, kodemartin requested changes
Hey @rjcortese! thank you very much for your tedious effort in putting this patch together. Testing is more than sufficient I reckon. But here are some recommendations that might improve the implementation:

* The new `struct` would fit well inside the `address` module. I therefore suggest it is nested therein, instead of having a separate `parsed_address` module.
* I propose the following small refactoring of `ParsedAddress`:
   - Use only a private field `label_token: HashMap<String, String>`.
   - Implement public "getter" methods to expose the components: E.g. `pub fn house(&self) -> Option<String>` wrapping the inner hashmap `get` method.
   
   This would have the following benefits:
   - It guarantees that the struct can be initialized only from an `AddressParserResponse`.
   - It is easier to maintain, in case of upstream changes, since we avoid double hard-coding the labels.

Also please add documentation to all types and methods following the [API guidelines](https://git.wappier.com/wappier/blockchain-adapter-service/-/merge_requests/2/diffs) to the extent possible.

2022-01-25 03:56 UTC, rjcortese commented
Thanks for the review!

I'm not sure about the suggestion to make it a wrapper around `label_token: HashMap<String, String>` with methods that expose the fields... at least for my use case. Which is just to have a dumb struct. And to do the processing into separate fields on struct creation.

It seems like if there was a getter method for each field it would have to iterate the `AddressParserResponse` for each access unless you cache the result somehow... but still have to iterate and search for the field in there at least for each different field you check via method.

The benefits of your proposal make sense though... maybe there is a way to do both?
Like, I could make all the fields private which would address the one issue.
And I could make a getter method for each field as well that would just return the private value.
However this would again repeat the labels.

Thoughts?

2022-02-08 14:18 UTC, rjcortese commented
Hey @kodemartin, I miss read some part of your above recommendations so some of my response doesn't make sense... my apologies.
Anyways, I've made changes based on your suggestions.

2022-02-10 08:02 UTC, kodemartin requested changes
Hi @rjcortese! I was planning to provide clarifications, sorry for the delay. Thank you for the changes.

I made a few minor suggestions about markdown for this iteration. Plus please run `cargo fmt` and push the generated changes.

There is an issue with the implementation of `From` I noticed now, but as I commented this can be treated independently of this PR.

2022-02-10 08:02 UTC, kodemartin commented on src/address.rs
> +        for (label, token) in &response {
This would best be consuming `response` (`for (label, token) in response`) to avoid cloning beneat, but this requires implementation of `IntoIterator` for `AddressParserResponse`. I will address this issue after this pr is merged though, unless you want to make the changes yourself.

2022-02-16 16:55 UTC, merged